### PR TITLE
Exclude ansible when performing os updates from ansible

### PR DESCRIPTION
**Pull request by chaitanyaenr**
Updating the ansible binary when a playbook is running will lead to
task failure.

### CODE REVIEW

**Comment by sjug** [comment]
What conditions does that cause failure? I've not seen that.

**Comment by chaitanyaenr** [comment]
this will cause failure when we don't have the latest ansible installed and try to update ansible from ansible playbook. Usually the os-kickstart installs packages on a remote machine that doesn't have ansible but when we already have ansible installed and try to update it, it fails. Take a look at https://github.com/ansible/ansible/issues/24059.

**Comment by sjug** [comment]
Yeah but on what image does it update ansible?

**Comment by chaitanyaenr** [comment]
on the host where we run all the roles

**Comment by chaitanyaenr** [comment]
superseded by #217

**Pull request closed without merging**
