### PR TITLE
Add pvc bound test

### PR DESCRIPTION
**Pull request by hongkailiu**
This test checks the latency of creating AWS-EBS-type PVCs.

### CODE REVIEW

**Comment by mffiedler** [comment]
Currently blocked on how to determine more granular volume bound time.   Need to re-visit that or close this PR out as something that is not going to happen

**Comment by jeremyeder** [comment]
Just FYI, lots of new storage metrics added to 3.7:  

https://docs.google.com/document/d/1Fh0T60T_y888LsRwC51CQHO75b2IZ3A34ZQS71s_F0g/edit#heading=h.9z6ourrhj8o

**Comment by hongkailiu** [comment]
Let us close this PR for now.
Reopen when we get a chance to revisit.

**Comment by hongkailiu** [comment]
@jeremyeder Thanks for the link.

**Pull request closed without merging**
