### PR TITLE
Traffic generation improvements

### PR DESCRIPTION
**Pull request by mffiedler**
- parameter-ize GUN_PORT
- don't hard code quickstart "example" string in routes searched

### CODE REVIEW

**Comment by mffiedler** [comment]
@sjug @vikaslaad PTAL

**Comment by sjug** [comment]
lgtm

**Comment by mffiedler** [comment]
@sabre1041 Needs a rebase.  Let me know if you want me to take care of it.

**Comment by mffiedler** [comment]
Closed in favor of #159 - same changes, but had to work around a merge.

**Pull request closed without merging**
