### PR TITLE
Log & security enhancement & a fix

### PR DESCRIPTION
**Pull request by qiliRedHat**
1. Log enhancement: added `ignore_log` flag to enable or disable command output written to log file (https://github.com/openshift/svt/issues/678) https://github.com/openshift/svt/pull/700/commits/2803e207b3b7c796f867e585c56ee0bb0acaa7ca

2. Log enhancement: set `ignore_log=True` for step whose output can be ignore, especially for positive false Errors. https://github.com/openshift/svt/pull/700/commits/2803e207b3b7c796f867e585c56ee0bb0acaa7ca

3. SlackIntegration enhancement: Add `info` and `error` function to SlackIntegration to aline with log output.  https://github.com/openshift/svt/pull/700/commits/82e96d495e29b3cd199754d77e0069f67bc5ede4

4. Fix a seldom happened issue found in recent test: Ensure login to init kubeconfig succcssful to all users. This is to avoid task being done by admin role(if a user login failed, default kubeconfig will fall into kubeadmin). If some user login fails, retry 10 times to ensure its success, if any of the user login failed after retry, stop the reliability test and ask user to check. https://github.com/openshift/svt/pull/700/commits/b41522b2b5a8ac54ddcfc8c607f5757909c635af

5. Security & Log enhancement: Mask password as `xxxx` to avoid credential exposed to log file or slack channel. https://github.com/openshift/svt/pull/700/commits/56871db7ddfc1ed9b1a5b6ead954573cca551141

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@mffiedler @paigerube14 Please help to review. This PR includes log and security enhancements together with a fix. @rpattath

**Comment by mffiedler** [comment]
I don't see a security or password masking change in the commits.  Is there a missing file?  or am I missing how this was implemented?

**Comment by mffiedler** [comment]
Possibly not part of this change, but I am seeing a strange repeating pattern in the log for oc get co:
`
2021-12-08 16:05:40,601 - INFO - [Task] User kubeadmin: check operators
2021-12-08 16:05:40,601 - INFO - => oc --kubeconfig /root/tmp/svt/reliability-v2/kubeconfigs/kubeconfig_kubeadmin get co --no-headers | awk '{print $1 $3 $4 $5 $7}' | grep -v TrueFalseFalse
2021-12-08 16:05:40,949 - ERROR - oc --kubeconfig /root/tmp/svt/reliability-v2/kubeconfigs/kubeconfig_kubeadmin get co --no-headers | awk '{print $1 $3 $4 $5 $7}' | grep -v TrueFalseFalse
 1 :
2021-12-08 16:05:40,949 - INFO - Cluster operators are healthy.
`
Based on check_operators the ERROR doesn't seem possible, but I have not investigated deeply.

**Comment by qiliRedHat** [comment]
> I don't see a security or password masking change in the commits. Is there a missing file? or am I missing how this was implemented?

Oh, sorry, I didn't push some of the recent changes.

**Comment by mffiedler** [comment]
LGTM - reviewed the code and tested.  Output looks good.   We still have the false ERROR for  oc --kubeconfig /root/tmp/svt/reliability-v2/kubeconfigs/kubeconfig_kubeadmin get co --no-headers | awk '{print $1 $3 $4 $5 $7}' | grep -v TrueFalseFalse -- but that can be fixed in a separate issue/PR

**Comment by paigerube14** [comment]
Noticed that the kubeconfig in the checked in config files points directly to your local downloads file @qiliRedHat. Can we take that out to be more generic? Like [here](https://github.com/qiliRedHat/svt/blob/log-enhancement/reliability/config/example_reliability.yaml)

Other than that same issue as Mike but looks good to me!

**Comment by qiliRedHat** [comment]
@mffiedler  I fixed the issue in your latest comment
https://github.com/openshift/svt/blob/e5c6b81994649e2f4c8e31e37bf88c262c31e1e4/reliability-v2/tasks/Tasks.py#L63
@paigerube14 I fixed the issue in your latest comment 
https://github.com/openshift/svt/blob/e5c6b81994649e2f4c8e31e37bf88c262c31e1e4/reliability-v2/config/example_reliability.yaml#L2-L5

@mffiedler I tested again and squashed the commits.

**Pull request merged**
