### PR TITLE
Add --raw option with no prefix

### PR DESCRIPTION
**Pull request by mffiedler**
Add a --raw option that does not prepend anything to the message.

@schituku please review

### CODE REVIEW

**Comment by pruan-rht** [comment]
LGTM

**Comment by mffiedler** [comment]
@anpingli found a problem with the line lengths when reading from files.  Need to update the PR to make raw mode use file lines as-is regardless of line length settings.  I pushed a container image that has a temporary solution but need a final solution that is not so hacky.

**Comment by mffiedler** [comment]
Updated commit  to only return the line read when the mode is raw.   Don't try to adjust the line length.

**Comment by mffiedler** [comment]
@schituku found a few issues

1. README needs to be  updated
2. The --raw flag still has some strange interactions with other options.   Need to make --raw exclusively work with --file and ignore other options like fixed and line length

**Comment by mffiedler** [comment]
@schituku PR updated.  Please take a look.

**Comment by anpingli** [comment]
Great

**Pull request merged**
