### PR TITLE
Add check-docker-images script

### PR DESCRIPTION
**Pull request by hongkailiu**
The added script can check if the docker images of a given version for logging stack are ready in registry for test. It is planned to run this script before deploying the stack.

### CODE REVIEW

**Comment by mffiedler** [comment]
@hongkailiu A couple of things:
1.  the base directory manual.steps needs to be refactored.  I never should have merged #244 which created that directory.   I suggest moving the scripts in this PR under the either the logging_metrics_performance directory or under utils.    Possibly utils/scripts.   I will open a separate issue to refactor the other content under manual.tests
2. Please add a description to the PR stating what problem it addresses and how it addresses it.

**Comment by hongkailiu** [comment]
1. I will move it into logging_metrics_performance in the next commit.
2. Done

**Comment by hongkailiu** [comment]
1. Done.

**Comment by hongkailiu** [comment]
CR -1
Need to remove the private reg check.

**Comment by hongkailiu** [comment]
Removed the part of checking private registry.

**Comment by hongkailiu** [comment]
Move to my own repo. Probally it wont be useful for others.
https://github.com/hongkailiu/svt-case-doc/tree/master/scripts

**Pull request closed without merging**
