### PR TITLE
Drain Node automation script

### PR DESCRIPTION
**Pull request by paigerube14**
For: https://issues.redhat.com/browse/OCPQE-2742

Automating test case: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-20084

### CODE REVIEW

**Comment by mffiedler** [comment]
@paigerube14 Sorry for the late review.  Can you please move the scripts to something like **openshift_scalability/content/drain_node**.   We are trying to keep general content out of openshift_scalability.   Some is already there and requires cleaning up, but new content should go under content/<test-name>

**Comment by paigerube14** [comment]
@mffiedler I moved the drainNode.sh file into the scripts under openshift_scalability. The content folder looks to be mostly yaml files used in the scripts. Is under the scripts folder ok? I could also make a drainNode folder under scripts, similar to what I I had added for pod density automation.  Should I also move the loop_drain_node.sh script that drainNode uses to start to clean up the general scalability folder?

**Comment by mffiedler** [comment]
Under scripts is ok.  Or create a folder under content (see content/logtest or content/centos-stress as examples).

**Comment by paigerube14** [comment]
@mffiedler I think this is ready for review

**Comment by mffiedler** [comment]
LGTM

**Comment by paigerube14** [comment]
Thanks for the review Mike!

**Pull request merged**
