### PR TITLE
Introduce dockerfile for grafana-ocp.

### PR DESCRIPTION
**Pull request by mrsiano**
In continuing to https://github.com/openshift/origin/pull/17037, submitting a PR with relevant dockerfile.

### CODE REVIEW

**Comment by mrsiano** [comment]
@openshift/svt

**Comment by mffiedler** [comment]
It would be cool to wrap this with an Openshift pod/deployment/rc definition

**Comment by mrsiano** [comment]
@mffiedler what do you mean, like plain folder ? otherwise could you share an example ?

**Comment by jeremyeder** [comment]
@mffiedler check the upstream issue, Clayton didn't want to carry the Dockerfile in Origin.  The template that uses the image generated by this Dockerfile is hopefully to be merged into Origin. in origin/#17037

**Comment by mffiedler** [comment]
Thanks, caught up on the upstream.  Will test dockerfile in conjunction with that PR

**Comment by mffiedler** [comment]
lgtm

**Pull request merged**
