### PR TITLE
Extend tests to enable running tests between hostip-to-hostip

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Add support to enable running test harness between any two hosts.
These hosts can be baremetal servers or VMs.

Also some improvements are being made as per pep8 guidelines,
for example removing extra white spaces, extra blank lines,
undesires spaces around '='.

### CODE REVIEW

**Comment by mffiedler** [comment]
@schituku Please take a look

**Comment by schituku** [comment]
@mffiedler tested this PR and it is good to go. Ran the entire regression tests and has no issues.
cc/ @vikaschoudhary16

**Comment by mffiedler** [comment]
@vikaschoudhary16 Needs a rebase.     /cc: @schituku

**Comment by vikaschoudhary16** [comment]
@mffiedler rebase done!!!

**Comment by mffiedler** [comment]
@schituku Please take one more look - no need for full regression, just make sure new merge looks sane.   I should have merged this first before your other changes, but got them out of order.    Mark this PR approved if you are ok with it.   @vikaschoudhary16 - thanks.

**Comment by vikaschoudhary16** [comment]
ping @mffiedler

**Pull request merged**
