### PR TITLE
Adding new and updating High Availability test scripts.

### PR DESCRIPTION
**Pull request by skordas**
Adding new test scripts
OCP-22208, OCP-22211, OCP-22212, OCP-22399

### CODE REVIEW

**Comment by skordas** [comment]
@schituku PTAL

**Comment by mffiedler** [comment]
@schituku Please review this PR.  Thanks.

**Comment by mffiedler** [comment]
@skordas  do you plan to move forward with this or should I close it?  (/cc: @schituku )

**Comment by mffiedler** [comment]
We can revisit this if we decide to move forward later.

**Pull request closed without merging**
