### PR TITLE
add list_all_resources to reliability tests

### PR DESCRIPTION
**Pull request by mehabhalodiya**
Fix: https://issues.redhat.com/browse/OCPQE-19542

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@mehabhalodiya Is this ready for review? You have the work in progress label. Are you still working on adding the script to the reliability config file as a task?

**Comment by mehabhalodiya** [comment]
@qiliRedHat You can help me by reviewing it.

**Comment by qiliRedHat** [comment]
@mehabhalodiya Please add a task in reliability.yaml to include this script and test it. If you just want to add the script first and add task in another pr, I'm good with it.

**Pull request merged**
