### PR TITLE
Dynamic loader

### PR DESCRIPTION
**Pull request by mrsiano**
we should merge this PR once #500 #504 will merge

### CODE REVIEW

**Comment by mrsiano** [comment]
/cc @jeremyeder @brancz 
this PR would give us the ability to scan the grafana assets form the cluster-monitoring-operator and use them accordingly

**Comment by brancz** [comment]
I'm busy all week with PromCon, if it does what you say it does I'm ok with merging once someone else gives this a lgtm :slightly_smiling_face:

**Comment by mffiedler** [comment]
@mrsiano Please squash the 19 commits.  Thanks.

**Comment by mrsiano** [comment]
@mffiedler done already..

**Comment by mffiedler** [comment]
@mrsiano Please resolve the merge conflict.

**Pull request merged**
