### PR TITLE
Added dependencies to svt readme

### PR DESCRIPTION
**Pull request by bfallonf**
As per conversation in this BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1456234

cc @jeremyeder

### CODE REVIEW

**Comment by jeremyeder** [comment]
For context, a customer requested more detail on building images to transfer into a disconnected environment.

@bfallonf the only thing I'd say is to make the language strong around how this is not supported in any way shape or form, regardless of whether it is production environment or not (In other words, you cannot call CEE and open a ticket against it).

That said, we'd like feedback via Issues and especially PRs to this repo.

**Comment by bfallonf** [comment]
Thanks @jeremyeder . I've updated the paragraph. Let me know if you have any suggestions to make it stronger, etc. I also changed the bit at the bottom asking for feedback to be more precise.

Also, let me know if this needs labels or whatever, or if it needs more.

**Comment by jeremyeder** [comment]
LGTM, long term goal is to migrate our tests into the Origin repo (which has already begun).  Those will be supported.

**Comment by bfallonf** [comment]
@jeremyeder Oops. Too used to the openshift-docs repo markup... I made it a heading, but smaller. Let me know if there's anything else. Thanks. Merge away if you like?

**Pull request merged**
