### PR TITLE
updating pod affinity config file variables

### PR DESCRIPTION
**Pull request by lenahorsley**
Jenkins job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/regression-test/97/console

### CODE REVIEW

**Comment by lenahorsley** [comment]
@paigerube14 @qiliRedHat

**Comment by paigerube14** [comment]
Want to add node density updates here as well

**Comment by lenahorsley** [comment]
Node affinity Jenkins job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/regression-test/100/console

Pod affinity Jenkins job:  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/regression-test/101/console

@qiliRedHat 
@paigerube14

**Pull request merged**
