### PR TITLE
Add multi-project support to mongodb test

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by hongkailiu** [comment]
@ekuric Let me know if you agree on the way to support multi-project.

**Comment by hongkailiu** [comment]
Example of pbench data:
http://pbench.dev.openshift.com/results/ip-172-31-11-25/pbench-user-benchmark_mongodb_storage_test_glusterfs-storage_workloada,workload_template_4096Mi_recordcount_1000_operationcount_1000_2018.06.11T18.41.12/1/reference-result/

**Comment by mffiedler** [comment]
@ekuric @hongkailiu Never saw a review on this one.  It needs merge conflicts resolved at a minimum if we still want it.

**Comment by hongkailiu** [comment]
Let us close it for the moment.
When Elko get stable version of a single project, we can review this again.
Elko also mentioned back in time that he suggests to create multi-projects via cluster loader.

**Comment by ekuric** [comment]
@hongkailiu @mffiedler I would merge this to give us multiproject support for this specific test, if necessary I can prepare new PR with these files, but I think they can go as is now, I did tests for multiproject mongo/ycsb. Please let know is this still possible to merge or there is need to create new PR. 
Thank you!

**Comment by mffiedler** [comment]
@hongkailiu Let me know how you want to proceed with this PR.   At a minimum it requires a rebase.

**Comment by hongkailiu** [comment]
@ekuric Have you pushed your latest code on mongo yet?
I can do the rebase afterwards. Thanks.

**Comment by hongkailiu** [comment]
Replaced by https://github.com/openshift/svt/pull/551/

**Pull request closed without merging**
