### PR TITLE
New golang cluster-loader config files for taints and toleration scalability testcase

### PR DESCRIPTION
**Pull request by wabouhamad**
GoLang cluster-loader Yaml configuration file for taints and toleration:
- openshift_scalability/config/golang/node-taints-pod-tolerations.yaml

Pod json config files for with tolerations for node taints:
- openshift_scalability/content/pod-hello-s1-taints-tolerations.json
- openshift_scalability/content/pod-hello-s2-taints-tolerations.json

### CODE REVIEW

**Comment by wabouhamad** [comment]
@mffiedler PTAL

**Comment by jeremyeder** [comment]
How are you tainting the nodes?

**Comment by wabouhamad** [comment]
@jeremyeder , yes, tainting both compute nodes:
oc adm taint nodes <node1> security=s1:NoSchedule
oc adm taint nodes <node2> security=s2:NoSchedule

**Comment by jeremyeder** [comment]
I mean where does the tainting occur?  It's not in this PR

**Comment by wabouhamad** [comment]
right now this is done either manually or in jenkins, but I can put these setup commands in a shell script that also triggers the golang cluster-loader.

**Comment by mffiedler** [comment]
Merging what we have so far.  @wabouhamad Please create an issue and JIRA card for automating the tainting.   Thanks.

**Pull request merged**
