### PR TITLE
Pod and Node Affinity updates

### PR DESCRIPTION
**Pull request by paigerube14**
These changes are adding both pod and node affinity test scripts.

- Added python and golang versions of cluster loader
- Making relative imports in yaml files 
- Adding python yaml files for python cluster loader 
- Add validation of expected number of pods in both pods and nodes based on nums set in yaml files not hard coded 
- This also includes using the 4.6 version of openshift-tests 

Also adding a script that helps install the openshift-tests binary (get_openshift_tests.sh )

### CODE REVIEW

**Comment by paigerube14** [comment]
@wabouhamad when you get a chance can you take a look and see if this what you were thinking about for some updates to these scripts? And also anything else I can add. Thanks!

**Review by mffiedler — APPROVED** [review]
LGTM - Some nitpick comments on the utility script.  But the real test changes are good - nice cleanup of these tests.

**Comment by mffiedler** [comment]
Tested python and golang.

**Comment by mffiedler** [comment]
The node test is passing for both python and golang.   The pod test passes for golang but fails for python.  Investigating.

**Comment by paigerube14** [comment]
> The node test is passing for both python and golang. The pod test passes for golang but fails for python. Investigating.

I hit the same issue I think. I added an "s" to the pause time in the pod-affinity.yaml file. I am going to add a README because the cluster loader needs to use python2 to properly decode in the utils.py script.

**Comment by mffiedler** [comment]
All tests working for me now...merging.

**Comment by paigerube14** [comment]
Thanks for reviewing this @mffiedler, much appreciated

**Pull request merged**
