### PR TITLE
Add workload without openshift template

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-25543

### CODE REVIEW

**Comment by qiliRedHat** [comment]
Test on jumphost
All resources are created and running
```
% oc get all -n dev-test-testuser-2-0
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                            READY   STATUS    RESTARTS   AGE
pod/http-perf-5648f4765-sfdtj   1/1     Running   0          36s

NAME                TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/http-perf   NodePort   172.30.157.36   <none>        8080:30875/TCP   25s

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/http-perf   1/1     1            1           36s

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/http-perf-5648f4765   1         1         1       36s

NAME                                 HOST/PORT                                                                   PATH   SERVICES    PORT   TERMINATION   WILDCARD
route.route.openshift.io/http-perf   http-perf-dev-test-testuser-2-0.apps.u8m2m4l5p6q9r6o.iar3.s1.devshift.org          http-perf   http                 None
```

**Comment by qiliRedHat** [comment]
@mehabhalodiya Would you help to review this test case?

**Review by mehabhalodiya — COMMENTED** [review]
LGTM!

**Pull request merged**
