### PR TITLE
Add logging-on-file support to log test tool

### PR DESCRIPTION
**Pull request by hongkailiu**
This is mainly for storage test. The case is to write logs on a file
backed up by a PVC.

### CODE REVIEW

**Comment by mffiedler** [comment]
@hongkailiu Nice.  Looks good to me.   Should we also add an rc (or statefulset?) template that sets up the PVC?

**Comment by hongkailiu** [comment]
The template is in my repo for the moment:
https://github.com/hongkailiu/svt-case-doc/blob/master/files/fio-template3.json

Thinking where to put in svt repo:
Ideally here:
https://github.com/openshift/svt/tree/master/openshift_scalability/content/fio

Because I will use the config file (for clsuter-loader) in the same folder but with the modified template as bove to use the image containing the logTestTool.

It has more changes than image because the configMap for the logTestTool so generating a new fio-template3.json.

Let me know your opinion.

**Comment by mffiedler** [comment]
Agree with the location.

**Comment by hongkailiu** [comment]
Uploaded the template.

**Pull request merged**
