### PR TITLE
[WIP] Add storage test for jenkins

### PR DESCRIPTION
**Pull request by hongkailiu**
It supports to test against one jenkins instance for now.

### CODE REVIEW

**Comment by hongkailiu** [comment]
@ekuric Please take a look.

**Comment by ekuric** [comment]
@hongkailiu I am going to test/check it, will update here ,

**Comment by hongkailiu** [comment]
@ekuric I will apply the comments for mongodb to here too.
Maybe we can forcus on mongodb and come back to this after mongo gets merged.

**Comment by hongkailiu** [comment]
[pbench data example](http://pbench.perf.lab.eng.bos.redhat.com/results/EC2::ip-172-31-26-32/pbench-user-benchmark_jenkins_storage_test_gp2_2018.05.03T22.48.36/1/reference-result/)

**Comment by hongkailiu** [comment]
Request changes from mongodb test:
1. redirect the iteration log to different files
2. oc new-project {{ test_project_name }} --skip-config-write=true

**Comment by hongkailiu** [comment]
update [pbench example](http://pbench.perf.lab.eng.bos.redhat.com/results/EC2::ip-172-31-8-206/pbench-user-benchmark_jenkins_storage_test_gp2_2018.05.04T21.56.08/1/reference-result/)

**Comment by hongkailiu** [comment]
@ekuric Most of the comments from mongo have been addressed.
Please try Jenkins case out when you got the chance.

**Comment by mffiedler** [comment]
@hongkailiu When you are satisfied with the recent changes, please squash to make final review easier.  Thanks.

**Pull request merged**
