### PR TITLE
duplciates profile using kube-burner

### PR DESCRIPTION
**Pull request by paigerube14**
A few updates to use kube-burner to run the duplicates profile 

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/regression-test/165/console

### CODE REVIEW

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Comment by paigerube14** [comment]
@qiliRedHat can you review and merge in your morning if it looks good to you! Thanks

**Comment by qiliRedHat** [comment]
Sorry I missed this.

**Pull request merged**
