### PR TITLE
Update node tuning operator test scripts to work with OCP 4.4

### PR DESCRIPTION
**Pull request by skordas**
Because NTO was rewritten to work in better way I needed to update test scripts for correct verification.
There is no change how to run scripts.

### CODE REVIEW

**Comment by skordas** [comment]
@mffiedler PTAL

**Comment by mffiedler** [comment]
@skordas Should I create a 4.3 branch to preserve the previous automation.  I did not see any conditionals for release specific behavior

**Comment by skordas** [comment]
@mffiedler 
yes... 3.x < current master will work here < 4.4
latest changes are working only with version >= 4.4

**Comment by mffiedler** [comment]
svt-4.3 branch created

**Pull request merged**
