### PR TITLE
Switch to pbench namespace after creating it using the template

### LINKED ISSUE #424: setup_pbench_pods.sh doesn't create pbench-agent pods in pbench namespace
https://github.com/openshift/svt/blob/master/openshift_tooling/pbench/setup_pbench_pods.sh#L87

@chaitanyaenr , PTAL

### PR DESCRIPTION
**Pull request by chaitanyaenr**
Fixes #424

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@jmencak PTAL.

**Comment by jmencak** [comment]
LGTM, however, you may want to use '-n pbench' when crreating resources, just in case someone/something doesn't change the namespaces while the script is running.

**Comment by mffiedler** [comment]
+1 to @jmencak suggestion

**Comment by chaitanyaenr** [comment]
@jmencak @mffiedler makes sense, updated the PR with the changes requested. PTAL.

**Pull request merged**
