### PR TITLE
Add script to setup tooling on openshift

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This commit adds a script which sets up tooling and checks if the
pods are in running state. This will be run by the jenkins job once
it receives a signal and parameters from the scale ci job.

### CODE REVIEW

**Comment by mffiedler** [comment]
In general, I think packages should either be installed via:
    - gold image creation (can we assume this will run on instances created from our images?)
    - package manager (yum, dnf, apt-get) as opposed to wget or curl.

**Comment by chaitanyaenr** [comment]
@mffiedler you are right, I will bake in the dependencies into the gold image.

**Comment by chaitanyaenr** [comment]
@mffiedler made the changes requested, jq will be baked into the gold image but I have left the jq installation steps in there just in case we want to use it on an instance not created using the gold image.

**Pull request merged**
