### PR TITLE
Logging update

### PR DESCRIPTION
**Pull request by rflorenc**
Use mapfile to create node list
Minor fixes in readme.md

### CODE REVIEW

**Comment by jmencak** [comment]
Tested deployment and started a basic test.  Quickly went through the code, definitely seems a PR for the better.

**Comment by mffiedler** [comment]
@wabouhamad Please review these commits

@rflorenc Let us know when you think this is ready to merge.

**Comment by rflorenc** [comment]
@mffiedler @wabouhamad thanks. Will do, don't merge for now.
I will still clean up/document a bit more.

**Comment by rflorenc** [comment]
@mffiedler, please merge.

**Comment by mffiedler** [comment]
@wabouhamad Please review.

**Pull request merged**
