### PR TITLE
Initial commit of conformance wrapper - work in progress

### PR DESCRIPTION
**Pull request by mffiedler**
Initial wrapper for e2e/performance tests for the SVT repo.   This is still a work in progress, but is far enough along to make an alpha available.

### CODE REVIEW

**Comment by mffiedler** [comment]
@vikaslaad Can you please take a look and see if you think this is sufficient for an alpha version?

**Comment by mffiedler** [comment]
This needs some additional testing - I'll resubmit.

**Comment by mffiedler** [comment]
OK, I think this is ready for review.  A lot of the serial tests fail node and inter-node affinity/anti-affinity tests.   I'll open an issue to investigate those.   The parallel tests have 1 failure:  [It] should appropriately serve a route that points to two services .   @vikaslaad  let me know if you have any comments.

**Comment by jeremyeder** [comment]
@mffiedler I'd like to see use of pbench to wrap these tests please.  https://github.com/openshift/svt/blob/master/openshift_scalability/pbench-register.sh

**Pull request merged**
