### PR TITLE
Add git workload for storage test

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by hongkailiu** [comment]
Example of pbench-data:
http://pbench.perf.lab.eng.bos.redhat.com/results/EC2::ip-172-31-40-2/pbench-user-benchmark_git_storage_test_3_gp2_2018.06.04T19.41.14/1/reference-result/result.txt

**Comment by mffiedler** [comment]
Suggest using the pbench-ansible registration (https://github.com/distributed-system-analysis/pbench/tree/master/contrib/ansible/openshift) as it will label nodes in the pbench results with their role.   It will make it easier to go back and look at results later.   Flexy has support for creating a pbench-controller but it is always on a separate instance which might be problematic.

**Comment by hongkailiu** [comment]
Thanks. I will give it a try.

**Comment by hongkailiu** [comment]
Done with the labeling of hosts in pbench.

http://pbench.perf.lab.eng.bos.redhat.com/results/EC2::ip-172-31-34-243/pbench-user-benchmark_git_storage_test_1_glusterfs-storage-block_2018.06.07T20.50.32/1/reference-result/tools-default/

**Comment by jeremyeder** [comment]
@hongkailiu this needs a review by the OSIO team, right?

**Comment by hongkailiu** [comment]
@jeremyeder 
I will ask for feedback on this case implementation via the mailing list.

**Pull request merged**
