### PR TITLE
WIP Changes for clusterloader unit testing framework

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Sample changes for clusterloader to include a fakeClient for unittesting.

### CODE REVIEW

**Comment by sjug** [comment]
So you're working on adding unit testing the deprecated tooling?

**Comment by ravisantoshgudimetla** [comment]
@sjug 
> So you're working on adding unit testing the deprecated tooling?

So, I thought this is what we are using for pbench, if not we should add a deprecation note, I guess.

>  How does your brand new PR already have merge conflicts?

It could be because my master was updated a long time back.

>  Where is the ticket that was created/approved to back this task?

There is nothing as of now. Started on it based our discussion during standup last week. I created an issue #235. I just did it on my spare time today.

**Comment by sjug** [comment]
It seems you're the only one on the team that isn't aware of the status of the python cluster loader. Perhaps if you had discussed this idea with anyone else they could have advised you of that.

**Comment by ravisantoshgudimetla** [comment]
> It seems you're the only one on the team that isn't aware of the status of the python cluster loader. 

Lol, I guess so. This is what I used last time for pbench. So, if this is not being maintained actively, we should add a deprecation note atleast.

> Perhaps if you had discussed this idea with anyone else they could have advised you of that.

Yeah, I just started working on another option for pbench and I looked at clusterloader code and then thought of making changes to make it a bit cleaner as per conversation the team had during standup or retrospective.

**Comment by jeremyeder** [comment]
Yeah, please leave the python cluster-loader alone (unless you are fixing a bug).  Closing this.

**Pull request closed without merging**
